#ifndef _GFPS_PROVIDER_ERRORS_H_
#define _GFPS_PROVIDER_ERRORS_H_

enum{
GFPS_SUCCESS,
GFPS_ERROR_EXEC_FAIL,
GFPS_ERROR_NULL,
GFPS_ERROR_INVALID_PARAM,
GFPS_ERROR_DATA_SIZE,    

GFPS_ERROR_UNAUTHENTICATED = 0x80,
GFPS_ERROR_INVALID_VALUE = 0x81,
GFPS_ERROR_NO_USER_CONSENT = 0x82
};
#define Gfps_CheckParm(code, exp) if (!(exp)) return (code)

#endif
