export SINGLE_WIRE_DOWNLOAD ?= 1
export DIRECT_TO_SINGLE_DLD ?= 0
export OTA_BIN_COMPRESSED ?= 1
include config/programmer_inflash/target.mk

ifeq ($(OTA_BIN_COMPRESSED),1)
export NEW_IMAGE_FLASH_OFFSET ?= 0x140000
else
export NEW_IMAGE_FLASH_OFFSET ?= 0x100000
endif
KBUILD_CPPFLAGS += -DNEW_IMAGE_FLASH_OFFSET=$(NEW_IMAGE_FLASH_OFFSET)

export APP_IMAGE_FLASH_OFFSET ?= 0x10000
KBUILD_CPPFLAGS += -D__APP_IMAGE_FLASH_OFFSET__=$(APP_IMAGE_FLASH_OFFSET) 

export APP_ENTRY_ADDRESS ?= 0x3c010000
KBUILD_CPPFLAGS += -DAPP_ENTRY_ADDRESS=$(APP_ENTRY_ADDRESS) 

core-y += tests/programmer_ext/ota_copy/
