

obj-y += tws_user_sdk/

#sdk include
subdir-ccflags-y += \
    -Iapps/key \
    -Iplatform/drivers/bt \
    -Iplatform/drivers/ana \
    -Iplatform/hal \
    -Iplatform/hal/best1305 \
    -Iservices/app_tws/inc \
    -Iservices/bt_if_enhanced/inc \
    -Iservices/app_ibrt/inc \
    -Iservices/multimedia/audio/codec/sbc/inc \
    -Iservices/nv_section/factory_section \
    -Iservices/tws_ibrt/inc \
    -Iutils/cqueue \
    -Iutils/heap


#stdf include
subdir-ccflags-y += \
    -IxOS_App\
	-IxOS_State\
	-IxOS_Timer\
	-IxOS_PT\
	-IxOS_Event\